version: '3.8'

services:
  api-service:
    build:
      context: ./api-service
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV:${NODE_ENV}
      - API_SERVICE_HOSTNAME:${API_SERVICE_HOSTNAME}
      - API_SERVICE_TCP_PORT:${API_SERVICE_TCP_PORT}
      - API_SERVICE_HTTP_PORT:${API_SERVICE_HTTP_PORT}
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: always
    command: yarn start:${NODE_ENV}
    depends_on:
      - game-service
    volumes:
      - ./api-service:/usr/src/app
    networks:
      - backend
      - default

  game-service:
    build:
      context: ./game-service
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV:${NODE_ENV}
      - GAME_SERVICE_HOSTNAME:${GAME_SERVICE_HOSTNAME}
      - GAME_SERVICE_PORT:${GAME_SERVICE_PORT}
#    hostname: "game-service"
    ports:
      - "3002:3002"
    restart: always
    command: yarn start:${NODE_ENV}
    volumes:
      - ./game-service:/usr/src/app
    networks:
      - backend
      - default

networks:
  backend:
    driver: bridge
  default:
    name: bitplay
    external: true
